'use strict';
const categories=['Vergi','SGK','Mevzuat','Ekonomi','İş Dünyası'];
const officialHosts=new Set(['www.tcmb.gov.tr','www.sgk.gov.tr','www.gib.gov.tr','www.resmigazete.gov.tr']);
function stored(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return Array.isArray(v)?v:fallback}catch{return fallback}}
function persist(key,v){try{localStorage.setItem(key,JSON.stringify(v))}catch{}}
let selected=stored('deneyim-topics',categories).filter(x=>categories.includes(x)),saved=new Set(stored('deneyim-saved',[])),items=[];
const $=s=>document.querySelector(s),feed=$('#feed');
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function date(raw){if(!raw)return 'Belirtilmedi';const d=new Date(raw.length===10?raw+'T12:00:00+03:00':raw);return Number.isNaN(d.getTime())?'Tarih doğrulanamadı':new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeZone:'Europe/Istanbul'}).format(d)}
function validURL(raw){try{const u=new URL(raw);return u.protocol==='https:'&&officialHosts.has(u.hostname)&&!u.username&&!u.password}catch{return false}}
function sourceLink(raw,label){const a=node('a',label);a.href=raw;a.target='_blank';a.rel='noopener noreferrer';return a}
function drawFilters(){const f=$('#filters');f.replaceChildren();for(const c of categories){const b=node('button',c,'chip'+(selected.includes(c)?' on':''));b.type='button';b.setAttribute('aria-pressed',String(selected.includes(c)));b.onclick=()=>{selected=selected.includes(c)?selected.filter(x=>x!==c):[...selected,c];persist('deneyim-topics',selected);drawFilters();drawFeed()};f.append(b)}}
function detail(x){const body=$('#detail-body');body.replaceChildren();body.append(node('span',x.category,'tag'),node('h2',x.title));const dl=node('dl');for(const [k,v] of [['Kaynak',x.source],['Yayın tarihi',date(x.published_at)],['Yürürlük tarihi',x.effective_at?date(x.effective_at):'Belirtilmedi — yayın tarihiyle aynı kabul edilmez.'],['İçerik türü','Resmî duyuru başlığı']])dl.append(node('dt',k),node('dd',v));body.append(dl,node('p','Bu kayıt resmî kaynağın başlığına ve bağlantısına dayanır. Tam metin, kapsam, istisnalar ve yürürlük hükümleri için kaynağı açın. Otomatik mevzuat yorumu veya işletme etkisi çıkarımı yapılmamıştır.','detail-note'),sourceLink(x.url,'Resmî duyurunun tam metnini aç ↗'));$('#detail').showModal()}
function drawFeed(){feed.replaceChildren();const q=$('#search').value.toLocaleLowerCase('tr-TR').trim();const visible=items.filter(x=>selected.includes(x.category)&&(!$('#saved-only').checked||saved.has(x.id))&&(!q||(x.title+' '+x.source).toLocaleLowerCase('tr-TR').includes(q)));$('#count').textContent=visible.length+' duyuru';if(!visible.length){feed.append(node('p',items.length?'Bu filtrelerle eşleşen duyuru yok. Kategori veya aramanızı değiştirebilirsiniz.':'Henüz alınmış resmî duyuru yok. Aşağıdaki kaynak bağlantılarını kullanabilirsiniz.','empty'));return}for(const x of visible){const a=node('article',undefined,'card'),top=node('div',undefined,'card-top'),save=node('button',saved.has(x.id)?'Kaydedildi ✓':'Kaydet +','save');save.setAttribute('aria-pressed',String(saved.has(x.id)));save.setAttribute('aria-label',x.title+' — '+(saved.has(x.id)?'kaydı kaldır':'kaydet'));save.onclick=()=>{saved.has(x.id)?saved.delete(x.id):saved.add(x.id);persist('deneyim-saved',[...saved]);drawFeed()};top.append(node('span',x.category,'tag'),save);const h=node('h3'),b=node('button',x.title,'headline');b.onclick=()=>detail(x);h.append(b);const bottom=node('div',undefined,'card-bottom');bottom.append(node('span',x.source),sourceLink(x.url,'Kaynağı aç ↗'));a.append(top,h,node('p','Yayın: '+date(x.published_at)+' · Yürürlük: '+(x.effective_at?date(x.effective_at):'Belirtilmedi'),'meta'),bottom);feed.append(a)}}
function drawSources(sources){$('#source-list').replaceChildren();for(const s of sources||[]){const d=node('div',undefined,'source'),head=node('div',undefined,'source-head');head.append(node('strong',s.name),node('span',s.status==='ok'?'Alındı':s.status==='manual'?'Bağlantı ile erişim':'Erişim hatası','state '+s.status));d.append(head);if(s.message)d.append(node('p',s.message));if(s.checked_at)d.append(node('p','Kontrol: '+date(s.checked_at)));if(validURL(s.url))d.append(sourceLink(s.url,'Resmî kaynağı aç ↗'));$('#source-list').append(d)}}
async function load(){const refresh=$('#refresh');refresh.disabled=true;try{const r=await fetch('./news.json',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();items=(data.items||[]).filter(x=>x.content_type==='official_headline'&&x.source_verified===true&&x.review_status==='source_only'&&x.title&&x.id&&x.published_at&&validURL(x.url)&&categories.includes(x.category)).sort((a,b)=>b.published_at.localeCompare(a.published_at));$('#status').textContent='Son başarılı toplama: '+date(data.updated_at)+' · '+items.length+' duyuru';const elapsed=Date.now()-Date.parse(data.updated_at);$('#freshness').hidden=Number.isFinite(elapsed)&&elapsed<36*3600000;$('#freshness').textContent='Veri toplama kaydı güncel değil. Son duyuruları resmî kaynaklardan kontrol edin.';drawSources(data.sources);drawFeed()}catch{$('#status').textContent='Veri dosyasına erişilemedi.';$('#freshness').hidden=false;$('#freshness').textContent='Haber akışı şu anda okunamıyor. İnternet bağlantınızı kontrol edip yeniden deneyin.';drawFeed()}finally{refresh.disabled=false}}
$('#search').addEventListener('input',drawFeed);$('#saved-only').addEventListener('change',drawFeed);$('#refresh').onclick=load;$('#close-detail').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});drawFilters();load();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
